paths:
  raw_data_dir: "./data/raw/"
  processed_data_path: "./data/processed/all_features.parquet"
  model_output_dir: "./results/models/"
  best_params_output_dir: "./results/params/"
  fig_output_dir: "./results/figures/"

processing:
  sample_rate_hz: 2000
  window_size_ms: 200
  window_step_ms: 50

filters:
  # Lists corresponding to files that we want to train on
  subjects: ["P005"]
  sessions: ["S002"]
  tasks: ["Default"]
  runs: ["001_eeg_up"]

modeling:
  # List of all Degrees of Freedom (DoF) to train models for.
  # TODO: The label processing function must produce columns matching these names.
  dof_list:
    - "wrist_flex_ext"
    - "wrist_pro_sup"
    - "thumb_flex_ext"
    - "thumb_abd_add"
    - "index_flex_ext"
    - "middle_flex_ext"
    - "ring_flex_ext"
    - "pinky_flex_ext"

  # Model to use: "LDA" or "RandomForest" or "DecisionTree" or "GaussianNB" or "SVM"
  model_type: "RandomForest"

  hyperparams:
    LDA:
      solver: "lsqr"
      shrinkage: "auto"
    SVM:
      loss: "squared_hinge"
      dual: "auto"
      max_iter: 10000
      C: 1.0
      random_state: 42
    GaussianNB: {}
    DecisionTree:
      max_depth: 10
      criterion: "gini"
    RandomForest:
      n_estimators: 100
      criterion: "gini"
      max_features: sqrt

  param_grids:
    LDA:
      solver: ["lsqr", "eigen"]
      shrinkage: ["auto"]
    SVM:
      # multi_class: ["ovr", "crammer_singer"]
      loss: ["hinge", "squared_hinge"]
      dual: ["auto"]
      max_iter: [10000, 50000]
      C: [0.01, 0.1, 1.0]
    GaussianNB: {}
    DecisionTree:
      max_depth: [10]
      criterion: ["gini"]
    RandomForest:
      n_estimators: [50, 100, 500]
      criterion: ["gini", "entropy", "log_loss"]
      max_features: ["sqrt", "log2"]

  # For reproducible train/test splits
  random_state: 42
  
  # Percentage of data to hold out for the test set
  test_size: 0.15
  val_size: 0.15

  hyperparam_search: True

  nested_cv: True

  num_trials: 10

  cv: 5